/*
 * This class was automatically generated with 
 * <a href="http://www.castor.org">Castor 1.3.1</a>, using an XML
 * Schema.
 * $Id$
 */

package edu.mayo.cts2.framework.model.service.exception;

/**
 * An exception generated by the CTS 2 service.
 *  
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings("serial")
public abstract class CTS2Exception extends edu.mayo.cts2.framework.model.exception.AbstractCTS2Exception 
implements java.io.Serializable
{


      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field _cts2Message.
     */
    private edu.mayo.cts2.framework.model.core.OpaqueData _cts2Message;

    /**
     * Field _severity.
     */
    private edu.mayo.cts2.framework.model.service.core.types.LoggingLevel _severity;


      //----------------/
     //- Constructors -/
    //----------------/

    public CTS2Exception() {
        super();
    }


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Overrides the java.lang.Object.equals method.
     * 
     * @param obj
     * @return true if the objects are equal.
     */
    @Override()
    public boolean equals(
            final Object obj) {
        if ( this == obj )
            return true;

        if (!super.equals(obj))
            return false;

        if (obj instanceof CTS2Exception) {

            CTS2Exception temp = (CTS2Exception)obj;
            if (this._cts2Message != null) {
                if (temp._cts2Message == null) return false;
                if (!this._cts2Message.equals(temp._cts2Message)) 
                    return false;
            } else if (temp._cts2Message != null)
                return false;
            if (this._severity != null) {
                if (temp._severity == null) return false;
                return this._severity.equals(temp._severity);
            } else return temp._severity == null;
        }
        return false;
    }

    /**
     * Returns the value of field 'cts2Message'.
     * 
     * @return the value of field 'Cts2Message'.
     */
    public edu.mayo.cts2.framework.model.core.OpaqueData getCts2Message(
    ) {
        return this._cts2Message;
    }

    /**
     * Returns the value of field 'severity'.
     * 
     * @return the value of field 'Severity'.
     */
    public edu.mayo.cts2.framework.model.service.core.types.LoggingLevel getSeverity(
    ) {
        return this._severity;
    }

    /**
     * Overrides the java.lang.Object.hashCode method.
     * <p>
     * The following steps came from <b>Effective Java Programming
     * Language Guide</b> by Joshua Bloch, Chapter 3
     * 
     * @return a hash code value for the object.
     */
    public int hashCode(
    ) {
        int result = super.hashCode();

        long tmp;
        if (_cts2Message != null) {
           result = 37 * result + _cts2Message.hashCode();
        }
        if (_severity != null) {
           result = 37 * result + _severity.hashCode();
        }

        return result;
    }

    /**
     * Method isValid.
     * 
     * @return true if this object is valid according to the schema
     */

    /**
     * Sets the value of field 'cts2Message'.
     * 
     * @param cts2Message the value of field 'cts2Message'.
     */
    public void setCts2Message(
            final edu.mayo.cts2.framework.model.core.OpaqueData cts2Message) {
        this._cts2Message = cts2Message;
    }

    /**
     * Sets the value of field 'severity'.
     * 
     * @param severity the value of field 'severity'.
     */
    public void setSeverity(
            final edu.mayo.cts2.framework.model.service.core.types.LoggingLevel severity) {
        this._severity = severity;
    }

    /**
     * 
     * 
     * @throws org.exolab.castor.xml.ValidationException if this
     * object is an invalid instance according to the schema
     */

}
